---
- name: Install PHP
  dnf:
    name:
      - php
      - php-mysqlnd
    state: present

- name: Restart Apache after PHP install
  service:
    name: httpd
    state: restarted

- name: create test page index.php
  copy:
    src: index.php
    dest: /var/www/html/index.php
  notify: Restart php
